{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '1.3', 'description': 'This app combines the observed data and the simulated data from the GEOGloWS ECMWF Streaamflow Services in Ecuador.', 'long_description': '', 'author': 'Jorge Luis Sanchez-Lozano, Karina Larco', 'author_email': 'jorgessanchez7@gmail.com, karynina3@gmail.com', 'url': '', 'license': ''}"
  dev_url: {{ data.get('url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: jorgessanchez7@gmail.com, karynina3@gmail.com
  keywords:
  - Hydrology
  - Time Series
  - Bias Correction
  - Hydrostats
  - GEOGloWS
  - Historical Validation Tool
  - Ecuador
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - geoglows
  - hydrostats
  - scipy
  - hs_restclient
source:
  path: ..
